LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := kernel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := kernel
LOCAL_MODULE_PATH := $(TARGET_OUT)
include $(BUILD_PREBUILT)
